# Generated by Django 5.2.7 on 2025-11-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("director", models.CharField(blank=True, max_length=200, null=True)),
                ("reparto", models.TextField(blank=True, null=True)),
                ("pais", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha_lanzamiento", models.IntegerField(blank=True, null=True)),
                ("duracion", models.CharField(blank=True, max_length=50, null=True)),
                ("categorias", models.CharField(blank=True, max_length=200, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "resultado_prediccion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("director", models.CharField(blank=True, max_length=200, null=True)),
                ("cast", models.TextField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("date_added", models.CharField(blank=True, max_length=100, null=True)),
                ("release_year", models.IntegerField(blank=True, null=True)),
                ("rating", models.CharField(blank=True, max_length=20, null=True)),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                ("listed_in", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("director", models.CharField(blank=True, max_length=200, null=True)),
                ("cast", models.TextField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("date_added", models.CharField(blank=True, max_length=100, null=True)),
                ("release_year", models.IntegerField(blank=True, null=True)),
                ("rating", models.CharField(blank=True, max_length=20, null=True)),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                ("listed_in", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
