# Generated by Django 5.2.7 on 2025-11-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netflix_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pelicula",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
    ]
